version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'

  database_test:
    container_name: postgres_test
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5423:5432'

  php:
    build:
      context: ./docker/php
    container_name: php_publisher_book
    volumes:
      - './:/var/www/html'

  nginx:
    container_name: nginx_publisher_book
    image: nginx:latest
    ports:
      - '888:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
